language: node_js
matrix:
  include:
    - node_js: "8"
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
install:
  - bash pika install
script:
  - bash pika build
  - bash pika test
  - bash pika package
after_success:
  - bash pika coverage